<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE filters [
    <!ELEMENT filters (#PCDATA|filter)*>
    <!ATTLIST filters count CDATA #REQUIRED>
    <!ELEMENT filter (#PCDATA|category|item|name|values)*>
    <!ELEMENT category (#PCDATA)>
    <!ELEMENT item (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT values (#PCDATA)>
    ]>
<filters count="4873">
    <filter>
        <item>1</item>
        <category>1</category>
        <name>1</name>
        <values>6,7,8,9,10</values>
    </filter>
    <filter>
        <item>1</item>
        <category>1</category>
        <name>2</name>
        <values>2</values>
    </filter>
    <filter>
        <item>1</item>
        <category>1</category>
        <name>3</name>
        <values>9</values>
    </filter>
    <filter>
        <item>1</item>
        <category>1</category>
        <name>4</name>
        <values>9</values>
    </filter>
    <filter>
        <item>1</item>
        <category>1</category>
        <name>5</name>
        <values>3</values>
    </filter>
    <filter>
        <item>1</item>
        <category>1</category>
        <name>6</name>
        <values>7</values>
    </filter>
    <filter>
        <item>1</item>
        <category>1</category>
        <name>7</name>
        <values>7</values>
    </filter>
    <filter>
        <item>1</item>
        <category>1</category>
        <name>8</name>
        <values>3</values>
    </filter>
    <filter>
        <item>1</item>
        <category>1</category>
        <name>10</name>
        <values>2</values>
    </filter>
    <filter>
        <item>1</item>
        <category>1</category>
        <name>11</name>
        <values>2</values>
    </filter>
    <filter>
        <item>1</item>
        <category>1</category>
        <name>12</name>
        <values>1,2,3,4,5,6</values>
    </filter>
    <filter>
        <item>1</item>
        <category>1</category>
        <name>13</name>
        <values>2</values>
    </filter>
    <filter>
        <item>1</item>
        <category>1</category>
        <name>14</name>
        <values>2,3,8</values>
    </filter>
    <filter>
        <item>1</item>
        <category>1</category>
        <name>15</name>
        <values>2</values>
    </filter>
    <filter>
        <item>1</item>
        <category>1</category>
        <name>16</name>
        <values>2</values>
    </filter>
    <filter>
        <item>2</item>
        <category>1</category>
        <name>1</name>
        <values>6,7,8,9,10</values>
    </filter>
    <filter>
        <item>2</item>
        <category>1</category>
        <name>2</name>
        <values>1</values>
    </filter>
    <filter>
        <item>2</item>
        <category>1</category>
        <name>3</name>
        <values>3</values>
    </filter>
    <filter>
        <item>2</item>
        <category>1</category>
        <name>4</name>
        <values>5,6</values>
    </filter>
    <filter>
        <item>2</item>
        <category>1</category>
        <name>5</name>
        <values>2</values>
    </filter>
    <filter>
        <item>2</item>
        <category>1</category>
        <name>6</name>
        <values>2</values>
    </filter>
    <filter>
        <item>2</item>
        <category>1</category>
        <name>7</name>
        <values>1</values>
    </filter>
    <filter>
        <item>2</item>
        <category>1</category>
        <name>8</name>
        <values>1</values>
    </filter>
    <filter>
        <item>2</item>
        <category>1</category>
        <name>9</name>
        <values>1</values>
    </filter>
    <filter>
        <item>2</item>
        <category>1</category>
        <name>10</name>
        <values>2,3</values>
    </filter>
    <filter>
        <item>2</item>
        <category>1</category>
        <name>11</name>
        <values>2</values>
    </filter>
    <filter>
        <item>2</item>
        <category>1</category>
        <name>12</name>
        <values>2</values>
    </filter>
    <filter>
        <item>2</item>
        <category>1</category>
        <name>13</name>
        <values>1,2</values>
    </filter>
    <filter>
        <item>2</item>
        <category>1</category>
        <name>14</name>
        <values>1,2,4</values>
    </filter>
    <filter>
        <item>2</item>
        <category>1</category>
        <name>15</name>
        <values>2</values>
    </filter>
    <filter>
        <item>2</item>
        <category>1</category>
        <name>16</name>
        <values>1</values>
    </filter>
    <filter>
        <item>3</item>
        <category>1</category>
        <name>1</name>
        <values>6,7,8,9,10</values>
    </filter>
    <filter>
        <item>3</item>
        <category>1</category>
        <name>2</name>
        <values>1</values>
    </filter>
    <filter>
        <item>3</item>
        <category>1</category>
        <name>3</name>
        <values>3</values>
    </filter>
    <filter>
        <item>3</item>
        <category>1</category>
        <name>4</name>
        <values>5,8</values>
    </filter>
    <filter>
        <item>3</item>
        <category>1</category>
        <name>5</name>
        <values>2</values>
    </filter>
    <filter>
        <item>3</item>
        <category>1</category>
        <name>6</name>
        <values>2</values>
    </filter>
    <filter>
        <item>3</item>
        <category>1</category>
        <name>7</name>
        <values>1,2</values>
    </filter>
    <filter>
        <item>3</item>
        <category>1</category>
        <name>8</name>
        <values>1</values>
    </filter>
    <filter>
        <item>3</item>
        <category>1</category>
        <name>9</name>
        <values>1</values>
    </filter>
    <filter>
        <item>3</item>
        <category>1</category>
        <name>10</name>
        <values>2,3</values>
    </filter>
    <filter>
        <item>3</item>
        <category>1</category>
        <name>11</name>
        <values>2</values>
    </filter>
    <filter>
        <item>3</item>
        <category>1</category>
        <name>12</name>
        <values>1,2</values>
    </filter>
    <filter>
        <item>3</item>
        <category>1</category>
        <name>13</name>
        <values>1,2</values>
    </filter>
    <filter>
        <item>3</item>
        <category>1</category>
        <name>14</name>
        <values>1</values>
    </filter>
    <filter>
        <item>4</item>
        <category>1</category>
        <name>1</name>
        <values>6,7,8,9,10</values>
    </filter>
    <filter>
        <item>4</item>
        <category>1</category>
        <name>2</name>
        <values>1</values>
    </filter>
    <filter>
        <item>4</item>
        <category>1</category>
        <name>3</name>
        <values>7,15</values>
    </filter>
    <filter>
        <item>4</item>
        <category>1</category>
        <name>4</name>
        <values>5,8</values>
    </filter>
    <filter>
        <item>4</item>
        <category>1</category>
        <name>5</name>
        <values>2</values>
    </filter>
    <filter>
        <item>4</item>
        <category>1</category>
        <name>6</name>
        <values>2</values>
    </filter>
    <filter>
        <item>4</item>
        <category>1</category>
        <name>7</name>
        <values>1,2</values>
    </filter>
    <filter>
        <item>4</item>
        <category>1</category>
        <name>8</name>
        <values>1</values>
    </filter>
    <filter>
        <item>4</item>
        <category>1</category>
        <name>9</name>
        <values>1</values>
    </filter>
    <filter>
        <item>4</item>
        <category>1</category>
        <name>10</name>
        <values>2,3</values>
    </filter>
    <filter>
        <item>4</item>
        <category>1</category>
        <name>11</name>
        <values>2</values>
    </filter>
    <filter>
        <item>4</item>
        <category>1</category>
        <name>12</name>
        <values>3</values>
    </filter>
    <filter>
        <item>4</item>
        <category>1</category>
        <name>13</name>
        <values>1,2</values>
    </filter>
    <filter>
        <item>4</item>
        <category>1</category>
        <name>14</name>
        <values>1,2,3</values>
    </filter>
    <filter>
        <item>4</item>
        <category>1</category>
        <name>15</name>
        <values>10</values>
    </filter>
    <filter>
        <item>4</item>
        <category>1</category>
        <name>16</name>
        <values>2</values>
    </filter>
    <filter>
        <item>5</item>
        <category>1</category>
        <name>1</name>
        <values>6,7,8,9,10</values>
    </filter>
    <filter>
        <item>5</item>
        <category>1</category>
        <name>2</name>
        <values>1</values>
    </filter>
    <filter>
        <item>5</item>
        <category>1</category>
        <name>3</name>
        <values>3</values>
    </filter>
    <filter>
        <item>5</item>
        <category>1</category>
        <name>4</name>
        <values>5,8</values>
    </filter>
    <filter>
        <item>5</item>
        <category>1</category>
        <name>5</name>
        <values>2</values>
    </filter>
    <filter>
        <item>5</item>
        <category>1</category>
        <name>6</name>
        <values>2</values>
    </filter>
    <filter>
        <item>5</item>
        <category>1</category>
        <name>7</name>
        <values>1,2</values>
    </filter>
    <filter>
        <item>5</item>
        <category>1</category>
        <name>8</name>
        <values>9</values>
    </filter>
    <filter>
        <item>5</item>
        <category>1</category>
        <name>9</name>
        <values>1</values>
    </filter>
    <filter>
        <item>5</item>
        <category>1</category>
        <name>10</name>
        <values>2,3</values>
    </filter>
    <filter>
        <item>5</item>
        <category>1</category>
        <name>11</name>
        <values>2</values>
    </filter>
    <filter>
        <item>5</item>
        <category>1</category>
        <name>12</name>
        <values>14</values>
    </filter>
    <filter>
        <item>5</item>
        <category>1</category>
        <name>13</name>
        <values>1,2</values>
    </filter>
    <filter>
        <item>5</item>
        <category>1</category>
        <name>14</name>
        <values>1,3</values>
    </filter>
    <filter>
        <item>6</item>
        <category>1</category>
        <name>1</name>
        <values>6,7,8,9,10</values>
    </filter>
    <filter>
        <item>6</item>
        <category>1</category>
        <name>2</name>
        <values>1</values>
    </filter>
    <filter>
        <item>6</item>
        <category>1</category>
        <name>3</name>
        <values>3</values>
    </filter>
    <filter>
        <item>6</item>
        <category>1</category>
        <name>4</name>
        <values>5</values>
    </filter>
    <filter>
        <item>6</item>
        <category>1</category>
        <name>5</name>
        <values>2</values>
    </filter>
    <filter>
        <item>6</item>
        <category>1</category>
        <name>6</name>
        <values>2</values>
    </filter>
    <filter>
        <item>6</item>
        <category>1</category>
        <name>7</name>
        <values>1,2</values>
    </filter>
    <filter>
        <item>6</item>
        <category>1</category>
        <name>8</name>
        <values>9</values>
    </filter>
    <filter>
        <item>6</item>
        <category>1</category>
        <name>9</name>
        <values>1</values>
    </filter>
    <filter>
        <item>6</item>
        <category>1</category>
        <name>10</name>
        <values>2,3</values>
    </filter>
    <filter>
        <item>6</item>
        <category>1</category>
        <name>11</name>
        <values>2</values>
    </filter>
    <filter>
        <item>6</item>
        <category>1</category>
        <name>12</name>
        <values>1,2,5,13,15,16</values>
    </filter>
    <filter>
        <item>6</item>
        <category>1</category>
        <name>13</name>
        <values>1,2</values>
    </filter>
    <filter>
        <item>6</item>
        <category>1</category>
        <name>14</name>
        <values>1</values>
    </filter>
    <filter>
        <item>6</item>
        <category>1</category>
        <name>15</name>
        <values>9,10,11</values>
    </filter>
    <filter>
        <item>6</item>
        <category>1</category>
        <name>16</name>
        <values>3</values>
    </filter>
    <filter>
        <item>7</item>
        <category>1</category>
        <name>1</name>
        <values>7,8,9,10</values>
    </filter>
    <filter>
        <item>7</item>
        <category>1</category>
        <name>2</name>
        <values>1</values>
    </filter>
    <filter>
        <item>7</item>
        <category>1</category>
        <name>3</name>
        <values>3</values>
    </filter>
    <filter>
        <item>7</item>
        <category>1</category>
        <name>4</name>
        <values>5,6,7</values>
    </filter>
    <filter>
        <item>7</item>
        <category>1</category>
        <name>5</name>
        <values>2</values>
    </filter>
    <filter>
        <item>7</item>
        <category>1</category>
        <name>6</name>
        <values>2</values>
    </filter>
    <filter>
        <item>7</item>
        <category>1</category>
        <name>7</name>
        <values>1,2</values>
    </filter>
    <filter>
        <item>7</item>
        <category>1</category>
        <name>8</name>
        <values>9</values>
    </filter>
    <filter>
        <item>7</item>
        <category>1</category>
        <name>9</name>
        <values>1</values>
    </filter>
    <filter>
        <item>7</item>
        <category>1</category>
        <name>10</name>
        <values>2,3</values>
    </filter>
    <filter>
        <item>7</item>
        <category>1</category>
        <name>11</name>
        <values>2</values>
    </filter>
    <filter>
        <item>7</item>
        <category>1</category>
        <name>12</name>
        <values>5,13,14,16</values>
    </filter>
    <filter>
        <item>7</item>
        <category>1</category>
        <name>13</name>
        <values>1,2</values>
    </filter>
    <filter>
        <item>7</item>
        <category>1</category>
        <name>14</name>
        <values>1,3</values>
    </filter>
    <filter>
        <item>7</item>
        <category>1</category>
        <name>15</name>
        <values>9</values>
    </filter>
    <filter>
        <item>7</item>
        <category>1</category>
        <name>16</name>
        <values>5</values>
    </filter>
    <filter>
        <item>8</item>
        <category>1</category>
        <name>1</name>
        <values>6,7,8</values>
    </filter>
    <filter>
        <item>8</item>
        <category>1</category>
        <name>2</name>
        <values>1</values>
    </filter>
    <filter>
        <item>8</item>
        <category>1</category>
        <name>3</name>
        <values>7</values>
    </filter>
    <filter>
        <item>8</item>
        <category>1</category>
        <name>4</name>
        <values>2,14</values>
    </filter>
    <filter>
        <item>8</item>
        <category>1</category>
        <name>5</name>
        <values>1</values>
    </filter>
    <filter>
        <item>8</item>
        <category>1</category>
        <name>6</name>
        <values>2,4</values>
    </filter>
    <filter>
        <item>8</item>
        <category>1</category>
        <name>7</name>
        <values>3</values>
    </filter>
    <filter>
        <item>8</item>
        <category>1</category>
        <name>8</name>
        <values>1</values>
    </filter>
    <filter>
        <item>8</item>
        <category>1</category>
        <name>9</name>
        <values>2</values>
    </filter>
    <filter>
        <item>8</item>
        <category>1</category>
        <name>10</name>
        <values>2</values>
    </filter>
    <filter>
        <item>8</item>
        <category>1</category>
        <name>11</name>
        <values>2</values>
    </filter>
    <filter>
        <item>8</item>
        <category>1</category>
        <name>12</name>
        <values>3</values>
    </filter>
    <filter>
        <item>8</item>
        <category>1</category>
        <name>13</name>
        <values>1,2</values>
    </filter>
    <filter>
        <item>8</item>
        <category>1</category>
        <name>14</name>
        <values>1,2,3</values>
    </filter>
    <filter>
        <item>8</item>
        <category>1</category>
        <name>15</name>
        <values>12</values>
    </filter>
    <filter>
        <item>8</item>
        <category>1</category>
        <name>16</name>
        <values>8</values>
    </filter>
    <filter>
        <item>9</item>
        <category>1</category>
        <name>1</name>
        <values>8,9,10</values>
    </filter>
    <filter>
        <item>9</item>
        <category>1</category>
        <name>2</name>
        <values>1</values>
    </filter>
    <filter>
        <item>9</item>
        <category>1</category>
        <name>3</name>
        <values>4,6,11</values>
    </filter>
    <filter>
        <item>9</item>
        <category>1</category>
        <name>4</name>
        <values>6,8,15</values>
    </filter>
    <filter>
        <item>9</item>
        <category>1</category>
        <name>5</name>
        <values>1</values>
    </filter>
    <filter>
        <item>9</item>
        <category>1</category>
        <name>6</name>
        <values>2</values>
    </filter>
    <filter>
        <item>9</item>
        <category>1</category>
        <name>7</name>
        <values>1,4</values>
    </filter>
    <filter>
        <item>9</item>
        <category>1</category>
        <name>8</name>
        <values>1</values>
    </filter>
    <filter>
        <item>9</item>
        <category>1</category>
        <name>9</name>
        <values>1</values>
    </filter>
    <filter>
        <item>9</item>
        <category>1</category>
        <name>10</name>
        <values>8</values>
    </filter>
    <filter>
        <item>9</item>
        <category>1</category>
        <name>11</name>
        <values>1</values>
    </filter>
    <filter>
        <item>9</item>
        <category>1</category>
        <name>12</name>
        <values>5,16,18</values>
    </filter>
    <filter>
        <item>9</item>
        <category>1</category>
        <name>13</name>
        <values>1,2</values>
    </filter>
    <filter>
        <item>9</item>
        <category>1</category>
        <name>14</name>
        <values>1,2,3</values>
    </filter>
    <filter>
        <item>9</item>
        <category>1</category>
        <name>15</name>
        <values>2</values>
    </filter>
    <filter>
        <item>9</item>
        <category>1</category>
        <name>16</name>
        <values>2</values>
    </filter>
    <filter>
        <item>10</item>
        <category>1</category>
        <name>1</name>
        <values>7,8,9,10</values>
    </filter>
    <filter>
        <item>10</item>
        <category>1</category>
        <name>2</name>
        <values>2</values>
    </filter>
    <filter>
        <item>10</item>
        <category>1</category>
        <name>3</name>
        <values>2</values>
    </filter>
    <filter>
        <item>10</item>
        <category>1</category>
        <name>4</name>
        <values>12</values>
    </filter>
    <filter>
        <item>10</item>
        <category>1</category>
        <name>5</name>
        <values>3</values>
    </filter>
    <filter>
        <item>10</item>
        <category>1</category>
        <name>6</name>
        <values>2</values>
    </filter>
    <filter>
        <item>10</item>
        <category>1</category>
        <name>7</name>
        <values>7</values>
    </filter>
    <filter>
        <item>10</item>
        <category>1</category>
        <name>8</name>
        <values>2</values>
    </filter>
    <filter>
        <item>10</item>
        <category>1</category>
        <name>10</name>
        <values>2</values>
    </filter>
    <filter>
        <item>10</item>
        <category>1</category>
        <name>11</name>
        <values>2</values>
    </filter>
    <filter>
        <item>10</item>
        <category>1</category>
        <name>12</name>
        <values>19</values>
    </filter>
    <filter>
        <item>10</item>
        <category>1</category>
        <name>13</name>
        <values>2</values>
    </filter>
    <filter>
        <item>10</item>
        <category>1</category>
        <name>14</name>
        <values>10</values>
    </filter>
    <filter>
        <item>11</item>
        <category>1</category>
        <name>1</name>
        <values>6,7,8,9</values>
    </filter>
    <filter>
        <item>11</item>
        <category>1</category>
        <name>2</name>
        <values>1</values>
    </filter>
    <filter>
        <item>11</item>
        <category>1</category>
        <name>3</name>
        <values>2,3</values>
    </filter>
    <filter>
        <item>11</item>
        <category>1</category>
        <name>4</name>
        <values>5,7</values>
    </filter>
    <filter>
        <item>11</item>
        <category>1</category>
        <name>5</name>
        <values>1</values>
    </filter>
    <filter>
        <item>11</item>
        <category>1</category>
        <name>6</name>
        <values>2</values>
    </filter>
    <filter>
        <item>11</item>
        <category>1</category>
        <name>7</name>
        <values>4</values>
    </filter>
    <filter>
        <item>11</item>
        <category>1</category>
        <name>8</name>
        <values>1</values>
    </filter>
    <filter>
        <item>11</item>
        <category>1</category>
        <name>9</name>
        <values>2</values>
    </filter>
    <filter>
        <item>11</item>
        <category>1</category>
        <name>10</name>
        <values>2</values>
    </filter>
    <filter>
        <item>11</item>
        <category>1</category>
        <name>11</name>
        <values>2</values>
    </filter>
    <filter>
        <item>11</item>
        <category>1</category>
        <name>12</name>
        <values>1,2,3,4,5,6,17,18</values>
    </filter>
    <filter>
        <item>11</item>
        <category>1</category>
        <name>13</name>
        <values>1,2</values>
    </filter>
    <filter>
        <item>11</item>
        <category>1</category>
        <name>14</name>
        <values>1,2,3</values>
    </filter>
    <filter>
        <item>11</item>
        <category>1</category>
        <name>15</name>
        <values>14</values>
    </filter>
    <filter>
        <item>11</item>
        <category>1</category>
        <name>16</name>
        <values>9</values>
    </filter>
    <filter>
        <item>12</item>
        <category>1</category>
        <name>1</name>
        <values>6,7,8,9</values>
    </filter>
    <filter>
        <item>12</item>
        <category>1</category>
        <name>2</name>
        <values>1,2</values>
    </filter>
    <filter>
        <item>12</item>
        <category>1</category>
        <name>3</name>
        <values>3,7,8</values>
    </filter>
    <filter>
        <item>12</item>
        <category>1</category>
        <name>4</name>
        <values>3,15</values>
    </filter>
    <filter>
        <item>12</item>
        <category>1</category>
        <name>5</name>
        <values>2,3</values>
    </filter>
    <filter>
        <item>12</item>
        <category>1</category>
        <name>6</name>
        <values>1</values>
    </filter>
    <filter>
        <item>12</item>
        <category>1</category>
        <name>7</name>
        <values>1,7</values>
    </filter>
    <filter>
        <item>12</item>
        <category>1</category>
        <name>8</name>
        <values>1</values>
    </filter>
    <filter>
        <item>12</item>
        <category>1</category>
        <name>9</name>
        <values>2</values>
    </filter>
    <filter>
        <item>12</item>
        <category>1</category>
        <name>10</name>
        <values>2</values>
    </filter>
    <filter>
        <item>12</item>
        <category>1</category>
        <name>11</name>
        <values>2</values>
    </filter>
    <filter>
        <item>12</item>
        <category>1</category>
        <name>12</name>
        <values>3,4,5,6</values>
    </filter>
    <filter>
        <item>12</item>
        <category>1</category>
        <name>13</name>
        <values>1,2</values>
    </filter>
    <filter>
        <item>12</item>
        <category>1</category>
        <name>14</name>
        <values>1,2</values>
    </filter>
    <filter>
        <item>12</item>
        <category>1</category>
        <name>15</name>
        <values>20</values>
    </filter>
    <filter>
        <item>12</item>
        <category>1</category>
        <name>16</name>
        <values>14</values>
    </filter>
	<filter>
        <item>13</item>
        <category>1</category>
        <name>1</name>
        <values>7,8,9</values>
    </filter>
    <filter>
        <item>13</item>
        <category>1</category>
        <name>2</name>
        <values>1</values>
    </filter>
    <filter>
        <item>13</item>
        <category>1</category>
        <name>3</name>
        <values>7,11</values>
    </filter>
    <filter>
        <item>13</item>
        <category>1</category>
        <name>4</name>
        <values>2,14,16</values>
    </filter>
    <filter>
        <item>13</item>
        <category>1</category>
        <name>5</name>
        <values>1</values>
    </filter>
    <filter>
        <item>13</item>
        <category>1</category>
        <name>6</name>
        <values>2</values>
    </filter>
    <filter>
        <item>13</item>
        <category>1</category>
        <name>7</name>
        <values>4,6</values>
    </filter>
    <filter>
        <item>13</item>
        <category>1</category>
        <name>8</name>
        <values>1</values>
    </filter>
    <filter>
        <item>13</item>
        <category>1</category>
        <name>9</name>
        <values>1</values>
    </filter>
    <filter>
        <item>13</item>
        <category>1</category>
        <name>10</name>
        <values>2</values>
    </filter>
    <filter>
        <item>13</item>
        <category>1</category>
        <name>11</name>
        <values>2</values>
    </filter>
    <filter>
        <item>13</item>
        <category>1</category>
        <name>12</name>
        <values>3,4,5,6,9,10,13</values>
    </filter>
    <filter>
        <item>13</item>
        <category>1</category>
        <name>13</name>
        <values>2</values>
    </filter>
    <filter>
        <item>13</item>
        <category>1</category>
        <name>14</name>
        <values>4,5,6,10</values>
    </filter>
    <filter>
        <item>13</item>
        <category>1</category>
        <name>15</name>
        <values>9</values>
    </filter>
    <filter>
        <item>13</item>
        <category>1</category>
        <name>16</name>
        <values>5</values>
    </filter>
	<filter>
        <item>14</item>
        <category>1</category>
        <name>1</name>
        <values>6,7,8,9</values>
    </filter>
	<filter>
        <item>14</item>
        <category>1</category>
        <name>2</name>
        <values>1</values>
    </filter>
    <filter>
        <item>14</item>
        <category>1</category>
        <name>3</name>
        <values>11</values>
    </filter>
    <filter>
        <item>14</item>
        <category>1</category>
        <name>4</name>
        <values>2,5</values>
    </filter>
    <filter>
        <item>14</item>
        <category>1</category>
        <name>5</name>
        <values>1</values>
    </filter>
    <filter>
        <item>14</item>
        <category>1</category>
        <name>6</name>
        <values>2</values>
    </filter>
    <filter>
        <item>14</item>
        <category>1</category>
        <name>7</name>
        <values>4</values>
    </filter>
    <filter>
        <item>14</item>
        <category>1</category>
        <name>8</name>
        <values>1</values>
    </filter>
    <filter>
        <item>14</item>
        <category>1</category>
        <name>9</name>
        <values>1</values>
    </filter>
    <filter>
        <item>14</item>
        <category>1</category>
        <name>10</name>
        <values>2</values>
    </filter>
    <filter>
        <item>14</item>
        <category>1</category>
        <name>11</name>
        <values>2</values>
    </filter>
    <filter>
        <item>14</item>
        <category>1</category>
        <name>12</name>
        <values>3,4,5,6,9,10</values>
    </filter>
    <filter>
        <item>14</item>
        <category>1</category>